name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Run metrics action
        uses: lowlighter/metrics@latest
        with:
          output_action: none

      - name: Push metrics
        run: |
          set +e
          git checkout metrics-renders
          git config user.name rojadesign
          git config user.email s0apii.ra@googlemail.com
          sudo mv /metrics_renders/* ./
          git add --all
          git commit -m "chore: automatically push metrics"
          git push
